import logging
logging.basicConfig(filename="application.log" , level=logging.INFO,format="%(levelname)s-%(message)s")

logging.info("Application started")
logging.info("User login successful")
logging.warning("Memory usage high")
logging.error("Database connection failed")
logging.info("Retry successful")
logging.error("Payment service unavailable")
logging.info("User logout successful")
logging.info("New user registered")
logging.warning("Disk space running low")
logging.info("Database connection established")
logging.error("Failed to fetch user data")
logging.info("User data fetched successfully")
logging.warning("API response time high")
logging.info("Payment processed successfully")
logging.error("Payment transaction failed")
logging.info("Application backup completed")
logging.info("User profile updated")
logging.warning("Multiple failed login attempts")
logging.error("Authentication service unavailable")
logging.info("Authentication service restored")
logging.info("New order created")
logging.info("Order confirmation sent")
logging.error("Email service failed")
logging.warning("Server CPU usage high")
logging.info("Email service restored")
logging.info("Order shipped successfully")
logging.error("File upload failed")
logging.info("File upload successful")
logging.warning("Session timeout approaching")
logging.info("Session renewed successfully")